### ISSUE TITLE
Fails for cargo run and cargo test

### ISSUE THREAD

**Issue by ratulb** [Shizcow/caller_modpath#2]
When I run - cargo run/test - I am getting the following stacktrace -

custom attribute panicked
 --> examples/invoke/src/otherfile.rs:2:5
  |
2 |     #[backend::test]
  |     ^^^^^^^^^^^^^^^^
  |
  = help: message: Failed to find internal UUID; rustc metacall probably faliled. Called as `rustc -Z unstable-options --pretty=expanded --color=never --extern backend=caller_modpath/target/debug/libbackend.so caller_modpath/examples/invoke/src/main.rs`. Stderr:
          error: Unrecognized option: 'pretty'

I am on - rustc 1.58.0-nightly (e269e6bf4 2021-10-26)

**Comment by Shizcow** [comment]
I've confirmed this issue. It appears to be new to 1.58.0 as rustc has dropped the pretty flag. Not sure if it's just changed (unstable options) but I'll take a closer look into this eventually.

**Comment by TheButlah** [comment]
Just discovered this crate - I haven't been able to find a single other crate that lets me access the modpath inside a proc macro.

Any guideance on how to fix the --pretty issue?
